name: VarSCAT
channels: 
- conda-forge
- bioconda
dependencies: 
- python=3.6.8
- pip
- pip: 
    - PyVCF3==1.0.2
    - biopython==1.79
    - pandas==1.1.5
    - pysam==0.18.0
    - ordered-set==4.0.2 
    - pyfaidx==0.6.4 
    - packaging==21.3
